Fixes #346 Cannot read properties of undefined (reading 'has') at simple-parser.js:90:30
nodemailer/mailparser pull request #347
Opened 2023-06-28 13:21 UTC by RomansBermans

2023-06-28 13:21 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/nodemailer/mailparser?pullRequest=347) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/nodemailer/mailparser?pullRequest=347) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/nodemailer/mailparser?pullRequest=347) it.</sub>

2023-06-30 12:13 UTC, andris9 requested changes
Could you replace optional chaining with a different approach? mailparser is used in all kinds of environments and optional chaining is a rather new feature and not supported by older Node versions.

2023-06-30 13:06 UTC, RomansBermans commented
Done.

2023-06-30 13:19 UTC, andris9 approved these changes

2023-06-30 13:25 UTC, merged

2023-06-30 13:38 UTC, RomansBermans commented
@andris9 just checking if you are going to make a new release 3.6.5 so it can be targeted as dependency? Thanks.